# Generated by Django 2.2.6 on 2020-05-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0005_auto_20191227_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='num_fake',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
